### ISSUE TITLE
Hamode does not update properly

### ISSUE THREAD

**Issue by bearydname** [acockburn/hadashboard#46]
So my issue is that when changing an input_select, either via hadashboard or on the HA page, if i refresh the dashboard manually it will highlight the correct one, but not when changing the input from the dashboard (both will light up) or from the HA web page, (the previous one will stay lit and the other one will not light up)

Until a refresh of the web-page when the correct status icon will be lit.

Script section in HA config:
```
script:
  home_status_evening:
    alias: "evening status"
    sequence:
     - service: input_select.select_option
       data:
         entity_id: input_select.home_status
         option: "evening"
  home_status_night:
    alias: "night status"
    sequence:
     - service: input_select.select_option
       data:
         entity_id: input_select.home_status
         option: "night"
```

input_select section in HA config:
```
input_select:
  home_status:
    name: "home status"
    options:
      - evening
      - night
    initial: night
```

Snip from my .erb: 

    </li>
    <li data-row="4" data-col="5" data-sizex="2" data-sizey="1">
      <div data-id="home_status_evening" data-view="Hamode" data-title="Kväll" data-icon="moon-o" data-changemode="evening" data-input="home_status"</$
    </li>
    <li data-row="4" data-col="7" data-sizex="2" data-sizey="1">
      <div data-id="home_status_night" data-view="Hamode" data-title="Natt" data-icon="star-o" data-changemode="night" data-input="home_status"</$
    </li>

I should also pointout that all other changes are detected from HA like device-tracker. (both ways)

What i "feel" is weird, from the hapush.py when changing the input_select:

2017-01-22 21:48:49,721 INFO script.home_status_evening -> evening
and the same for switching to night
2017-01-22 21:48:49,721 INFO script.home_status_evening -> night

But should it not be script.home_status_night?

anyways, let me know if you need anything else!
